package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("out", "version.go", "output file path")
	pkg := flag.String("pkg", "version", "Go package name")
	flag.Parse()

	projectRoot, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("failed to find project root: %w", err)
	}

	versionBytes, err := os.ReadFile(filepath.Join(projectRoot, "VERSION"))
	if err != nil {
		return fmt.Errorf("failed to read VERSION file: %w", err)
	}

	version := ""
	for _, line := range strings.Split(string(versionBytes), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			version = line
			break
		}
	}
	if version == "" {
		return fmt.Errorf("no version found in VERSION file")
	}

	commitSHA, err := runGit(projectRoot, "rev-parse", "HEAD")
	if err != nil {
		return fmt.Errorf("failed to get git commit SHA: %w", err)
	}

	buildDate := time.Now().UTC().Format(time.RFC3339)

	dirtyOut, err := runGit(projectRoot, "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("failed to check git status: %w", err)
	}
	buildInfo := ""
	if dirtyOut != "" {
		buildInfo = "dirty"
	}

	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package %s

var (
	Version   = %q
	CommitSHA = %q
	BuildDate = %q
	BuildInfo = %q
)
`, *pkg, version, commitSHA, buildDate, buildInfo)

	if err := os.WriteFile(*out, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", *out, err)
	}

	fmt.Printf("Generated %s: %s (commit: %s)\n", *out, version, commitSHA[:min(7, len(commitSHA))])
	return nil
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if info, err := os.Stat(filepath.Join(dir, "VERSION")); err == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("VERSION file not found")
		}
		dir = parent
	}
}

func runGit(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}
