package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	version "github.com/lczyk/version/go"
)

// SemVer 2.0.0, https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
var semverRE = regexp.MustCompile(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`)

//go:generate go run . -out version_gen.go -pkg main -init

var (
	Version   string
	CommitSHA string
	BuildDate string
	BuildInfo string
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("out", "version.go", "output file path")
	pkg := flag.String("pkg", "version", "Go package name")
	asInit := flag.Bool("init", false, "emit func init() assigning existing package vars instead of var declarations")
	showVersion := flag.Bool("version", false, "print version and exit")
	flag.Parse()

	if *showVersion {
		fmt.Printf("generate-version %s\n",
			version.FormatVersion(Version, CommitSHA, BuildDate, BuildInfo))
		return nil
	}

	projectRoot, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("failed to find project root: %w", err)
	}

	versionBytes, err := os.ReadFile(filepath.Join(projectRoot, "VERSION"))
	if err != nil {
		return fmt.Errorf("failed to read VERSION file: %w", err)
	}

	version := ""
	for _, line := range strings.Split(string(versionBytes), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			version = line
			break
		}
	}
	if version == "" {
		return fmt.Errorf("no version found in VERSION file")
	}
	if !semverRE.MatchString(version) {
		return fmt.Errorf("VERSION %q is not a valid SemVer 2.0.0 string (https://semver.org)", version)
	}

	commitSHA, err := runGit(projectRoot, "rev-parse", "HEAD")
	if err != nil {
		return fmt.Errorf("failed to get git commit SHA: %w", err)
	}

	buildDate := time.Now().UTC().Format(time.RFC3339)

	dirtyOut, err := runGit(projectRoot, "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("failed to check git status: %w", err)
	}
	buildInfo := ""
	if dirtyOut != "" {
		buildInfo = "dirty"
	}

	open, indent, close := "var (", "\t", ")"
	if *asInit {
		open, indent, close = "func init() {", "\t", "}"
	}
	body := ""
	for _, kv := range [][2]string{
		{"Version", version}, {"CommitSHA", commitSHA},
		{"BuildDate", buildDate}, {"BuildInfo", buildInfo},
	} {
		body += fmt.Sprintf("%s%s = %q\n", indent, kv[0], kv[1])
	}
	raw := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\n\npackage %s\n\n%s\n%s%s\n",
		*pkg, open, body, close)
	formatted, err := format.Source([]byte(raw))
	if err != nil {
		return fmt.Errorf("failed to format generated source: %w", err)
	}
	content := string(formatted)

	if err := os.WriteFile(*out, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", *out, err)
	}

	fmt.Printf("Generated %s: %s (commit: %s)\n", *out, version, commitSHA[:min(7, len(commitSHA))])
	return nil
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if info, err := os.Stat(filepath.Join(dir, "VERSION")); err == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("VERSION file not found")
		}
		dir = parent
	}
}

func runGit(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}
