"""Generator: writes _version.py with the four named values from VERSION + git state.

Mirror of `go/cmd/generate-version`. See SPEC §5–§7.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import subprocess
import sys
from pathlib import Path

# SemVer 2.0.0, https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
_SEMVER_RE = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?"
    r"(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
)

_TEMPLATE = """\
# Code generated by generate-version; DO NOT EDIT.

version = {version!r}
commit_sha = {commit_sha!r}
build_date = {build_date!r}
build_info = {build_info!r}
"""


def find_project_root(start: Path) -> Path:
    cur = start.resolve()
    while True:
        if (cur / "VERSION").is_file():
            return cur
        if cur.parent == cur:
            raise FileNotFoundError("VERSION file not found")
        cur = cur.parent


def read_version(version_file: Path) -> str:
    for raw in version_file.read_text().splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            if not _SEMVER_RE.match(line):
                raise ValueError(
                    f"VERSION {line!r} is not a valid SemVer 2.0.0 string (https://semver.org)"
                )
            return line
    raise ValueError("no version found in VERSION file")


def run_git(cwd: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=True,
    )
    return out.stdout.strip()


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate _version.py from VERSION + git state."
    )
    p.add_argument(
        "--out", default="_version.py", help="output file path (default: _version.py)"
    )
    p.add_argument(
        "--version", action="store_true", help="print generate-version's own version and exit"
    )
    args = p.parse_args(argv)

    if args.version:
        from . import _version as _v
        from ._format import format_version

        print(f"generate-version {format_version(_v.version, _v.commit_sha, _v.build_date, _v.build_info)}")
        return 0

    try:
        root = find_project_root(Path.cwd())
        version = read_version(root / "VERSION")
        commit_sha = run_git(root, "rev-parse", "HEAD")
        dirty = run_git(root, "status", "--porcelain")
    except (FileNotFoundError, ValueError, subprocess.CalledProcessError) as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1

    build_date = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    build_info = "dirty" if dirty else ""

    Path(args.out).write_text(
        _TEMPLATE.format(
            version=version,
            commit_sha=commit_sha,
            build_date=build_date,
            build_info=build_info,
        )
    )
    short = commit_sha[: min(7, len(commit_sha))]
    print(f"Generated {args.out}: {version} (commit: {short})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
